/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface PreviousContractInterface extends ethers.utils.Interface {
  functions: {
    "resetStakeTimeMigrateState(address)": FunctionFragment;
    "getWhitelist(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "resetStakeTimeMigrateState",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getWhitelist",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "resetStakeTimeMigrateState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhitelist",
    data: BytesLike
  ): Result;

  events: {};
}

export class PreviousContract extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: PreviousContractInterface;

  functions: {
    resetStakeTimeMigrateState(
      addr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getWhitelist(
      addr: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  resetStakeTimeMigrateState(
    addr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getWhitelist(addr: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    resetStakeTimeMigrateState(
      addr: string,
      overrides?: Overrides
    ): Promise<{
      startTimestamp: BigNumber;
      lastTimestamp: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    getWhitelist(addr: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    resetStakeTimeMigrateState(addr: string): Promise<BigNumber>;
    getWhitelist(addr: string): Promise<BigNumber>;
  };

  populateTransaction: {
    resetStakeTimeMigrateState(addr: string): Promise<PopulatedTransaction>;
    getWhitelist(addr: string): Promise<PopulatedTransaction>;
  };
}
