/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import { PreviousContract } from "./PreviousContract";

export class PreviousContractFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PreviousContract {
    return new Contract(address, _abi, signerOrProvider) as PreviousContract;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address"
      }
    ],
    name: "resetStakeTimeMigrateState",
    outputs: [
      {
        internalType: "uint256",
        name: "startTimestamp",
        type: "uint256"
      },
      {
        internalType: "uint256",
        name: "lastTimestamp",
        type: "uint256"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address"
      }
    ],
    name: "getWhitelist",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
